### ISSUE TITLE
Simple, start-up code in using MoonMap.js

### ISSUE THREAD

**Issue by lynnellneri** [mitch-seymour/moonmap#1]
Hello! Very nice work! I am about to use this plugin. However, I am quite puzzled as the site don't offer some sample code to work on.

While experimenting on how to use it, and also by Inspecting Elements of your live examples in http://moonmapjs.com/, I figured out the code to start on:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--  MoonMap CSS -->
    <link rel="stylesheet" type="text/css" href="css/MoonMap.css" />
</head>
<body>
    <div id="demo" class="orbit-center">
        <span class="center-title">Phase 1</span>
    </div>

    <script type="text/javascript" src="js/MoonMap.min.js"></script>
    <script>
        map1 = new MoonMap('#demo', {
            n: 4,
            radius: 100
        });
    </script>
</body>
</html>
```

However, that's the most basic example I was able to came up with while experimenting. I'll surely wait for the updates of the documentation. And also, I am still basic at JavaScript.

**Comment by mitch-seymour** [comment]
Thanks for the feedback! I have updated the README with some examples on how to use this plugin. If you would like to see any new features, please let me know :)

**Comment by lynnellneri** [comment]
Wow! Nice! It's super informative :)

By the way, how do you make a certain moon active? Is it achievable by assigning a class to the moon DOM or only through JavaScript? I just wanted to make only one (static) active moon :)

**Comment by lynnellneri** [comment]
Also, how do I make the text inside the moons visible even if there are not active? :)

**Comment by lynnellneri** [comment]
Moreover, where does the start of the placement of the moons begin? Is there any way to customize it so that the moons are placed starting at 12 o'clock position?

**Comment by lynnellneri** [comment]
Also, can I place a text inside the moon other than the numbers? Like a link or something or an image perhaps? :)

Sorry, I really do have lots of questions :)

**Comment by mitch-seymour** [comment]
You can make a moon active by just applying the active class (**active** by default, but you can override this with the **activeClass** parameter) to the appropriate moon. Also, you can make the text visible by removing the **font-size: 0** rule in the moonMap.css stylesheet. 

Regarding the text inside the moons, you can put whatever content you want in each moon; it's up to you. Finally, I just added a new parameter that will allow you to specify the start angle. The following example is the equivalent of starting the moons at the 12 o'clock position:

``` js
var map = new MoonMap('#center', {
  moonSelector: '.moonSelector',
  radius: 140,
  startAngle: 90
});
```

Here is a quick reference for specifying the start angle.

<img src="http://moonmapjs.com/www/img/angles.gif" alt="image of angles around a circle" height="260px">

**Comment by lynnellneri** [comment]
Thanks! It's a very great help. However, I am puzzled with making a moon active. I tried adding `class="active"` to the moonselector that I wanted to be the active. But still it does not work.

All I wanted to do is to make the first moon created to the active. That's it. It's constant.

Moreover, the moons are not responsive to the size of it's content and neither is it vertically aligned to middle, nor it supports content has new line. Here's an example:

![Sample implementaton](http://i.imgur.com/ayFPCBe.png)
